services:
  - type: web
    name: nyra-virtual-ai-makeup-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Streamlit_App/app.py
    build:
      packages:
        - libgl1-mesa-glx
        - libglib2.0-0
        - libsm6
        - libxrender1
        - libxext6
